### ISSUE TITLE
Support DocumentTermMatrix objects as input?

### ISSUE THREAD

**Issue by alexpghayes** [RoheLab/vsp#10]
Including some different defaults to estimate LDA.

**Comment by fchen365** [comment]
I think the current implementation already accepts `DocumentTermMatrix` objects, because a `DocumentTermMatrix` is just an extension of `sparseMatrix`.

**Comment by mscbuck** [comment]
> I think the current implementation already accepts `DocumentTermMatrix` objects, because a `DocumentTermMatrix` is just an extension of `sparseMatrix`.

I believe this is correct (I've used this package on DTM matrices coming from packages such as `text2vec`, which by default use sparse matrix format).

**Comment by alexpghayes** [comment]
Actually I do think a method with different defaults is a good idea, even if no type coercion is necessary.

**Comment by alexpghayes** [comment]
@karlrohe what are the recommended centering and scaling steps for LDA again?
