### ISSUE TITLE
Is RSpectra::eigs() more efficient than RSpectra::svds() for symmetric matrices?

### ISSUE THREAD

**Issue by alexpghayes** [RoheLab/vsp#31]
Is so, we should take advantage of this. @karlrohe do you know the computational complexities of these things?

**Comment by karlrohe** [comment]
svds just does some fancy re-packaging of eigs (i think).  so, use eigs when it is symmetric.  use svds when it is not.

**Comment by yixuan** [comment]
I came across this issue by accident, and here is the answer. As Karl said, when the matrix is symmetric, `svds()` is equivalent to `eigs_sym()` with one exception: singular values are always nonnegative, so if some eigenvalues are negative, their signs will be moved to the right singular vectors. Despite this difference, the performance of the two functions are almost identical for symmetric matrices.

**Comment by karlrohe** [comment]
Thanks @yixuan!
