### ISSUE TITLE
if A has negative elements

### ISSUE THREAD

**Issue by karlrohe** [RoheLab/vsp#37]
if A has negative elements, then we should compute rs and cs as 
rs = rowSums(abs(A))
cs = colSums(abs(A))

otherwise, with default normalization=T... 

In addition: Warning messages:
1: In sqrt(rsA + tau_r) : NaNs produced
2: In sqrt(csA + tau_c) : NaNs produced

**Comment by alexpghayes** [comment]
Duplicate of #13
