### ISSUE TITLE
Figure out issue with signs in B

### ISSUE THREAD

**Issue by alexpghayes** [RoheLab/vsp#39]
Per @MuzheZeng's example at https://gist.github.com/MuzheZeng/846e5473dddc09616b3451055b420048

**Comment by alexpghayes** [comment]
@MuzheZeng have you had a change to look at the code and see if it's doing something wrong? Alternatively, can you send me the most recent copy of the paper -- I only have the version from several months ago so I'm not even sure if what I've implemented is what's in the paper anymore.

**Comment by karlrohe** [comment]
the distribution of Z is symmetric.  Make it asymmetric, that should fix it…






On Apr 15, 2020, at 10:31 AM, alex hayes <notifications@github.com<mailto:notifications@github.com>> wrote:



@MuzheZeng<https://github.com/MuzheZeng> have you had a change to look at the code and see if it's doing something wrong? Alternatively, can you send me the most recent copy of the paper -- I only have the version from several months ago so I'm not even sure if what I've implemented is what's in the paper anymore.

**Comment by alexpghayes** [comment]
I think the issue here is #48. Between upcoming fixes for #48, and tests for #46 we should catch whatever the issue is.
