### ISSUE TITLE
A better approach to centering

### ISSUE THREAD

**Issue by alexpghayes** [RoheLab/vsp#44]
Karl from lab meeting:

(I - n^{-1} 1 1')A 
that is row centering
A ~ UDV'
(I - n^{-1} 1 1')  A ~ (I - n^{-1} 1 1')  UDV'
so... we can svd(A)
then column center U

Then cholesky?? to reorthogonalize. (QR?)

**Comment by alexpghayes** [comment]
cc @karlrohe @MuzheZeng I am very on board with implementing this change but would prefer that someone else sort out the mathematical details and send me a quick writeup, rather than figuring them out myself.

**Comment by MuzheZeng** [comment]
@alexpghayes I emailed you.
