### ISSUE TITLE
[Suggest] Provide an option to re-order the columns of output Y 

### ISSUE THREAD

**Issue by fchen365** [RoheLab/vsp#55]
In the current implementation, row and column factors are not necessarily matched, because the middle `B` matrix is not strong diagonally dominant (see Fig. 1). We should provide an option to re-order the column of `B` (also that of `Y`, and `R_V`), so that `B` can be (closer to) diagonally dominant (see Fig. 2). This means: the row/column factors are matched.
[Fig. 1.pdf](https://github.com/RoheLab/vsp/files/5461857/Fig.1.pdf)
[Fig. 2.pdf](https://github.com/RoheLab/vsp/files/5461858/Fig.2.pdf)

To this end, add the following code as the last step of `vsp`. 

```{r}
#' @importFrom clue solve_LSAP
perm = as.integer(clue::solve_LSAP(pmax(as.matrix(vtm$B), 0), maximum = TRUE))
vtm$B <- vtm$B[,perm]
vtm$Y <- vtm$Y[,perm]
vtm$R_V <- vtm$R_V[,perm]
```

**Comment by alexpghayes** [comment]
```
perm = as.integer(clue::solve_LSAP(abs(x) + 0.0000001, maximum = TRUE))
```

works a little better for me in cases where there are many negative elements in B, but still isn't great

**Comment by alexpghayes** [comment]
note that we will also have to permute the rownames and colnames by hand as well when we seriate

**Comment by alexpghayes** [comment]
@fchen365 do this need to be done only for `Y` or also for `Z`? can you explain a little more what's going on here?

**Comment by fchen365** [comment]
I think we need to only permute `Y` (to match with (`Z`). 
In the code I provided, `vtm` is the output of `vsp()`. `perm` is a vector of length `k`. It contains an ordering of the columns of `Y`. For example, if `perm[1]` is 2, then we match the 2nd column of `Y` with the 1st column of `Z`. 
Does this make sense?

**Comment by alexpghayes** [comment]
Revisiting this, and unfortunately I can't follow what the plan was anymore.

**Comment by ravwojdyla** [comment]
@alexpghayes I have run into this problem as well. Also afait you can see it even on a dummy Iris data. I read the other issues:
 * https://github.com/RoheLab/vsp/issues/45
 * https://github.com/RoheLab/vsp/issues/36

But to be honest it's not clear to me what's the right way to handle this problem in VSP (with 2-3 suggestions listed in the issues). Do you have any recommendations please?

And here's an example of my $\hat{B}$:

![image](https://user-images.githubusercontent.com/1419010/177884650-1d9fe679-ff33-4f15-a12b-d09605b8ea62.png)

**Comment by alexpghayes** [comment]
Can you start a new issue with your full implementation and a comparison to the `B` from the R implementation?
