### ISSUE TITLE
[Suggest] add option to turn on/off the "normalize" in varimax rotation 

### ISSUE THREAD

**Issue by fchen365** [RoheLab/vsp#60]
It would be nice to allow an option to turn on/off the "normalize" in varimax rotation.

**Comment by karlrohe** [comment]
+1.  This would be great.  In fact, I just came here to make a new issue to request this!  👍

**Comment by alexpghayes** [comment]
Will tackle this by the end of the week, I want to play around with kaiser normalization as well.
