### ISSUE TITLE
plot_svd_v and _u sample with leverage

### ISSUE THREAD

**Issue by karlrohe** [RoheLab/vsp#65]
Could plot_svd_v and plot_svd_u subsample via leverage?  plot_varimax_z_pairs does this and it works really well.

**Comment by alexpghayes** [comment]
So the current plot is `row index ~ u[i, j]`. Do you just want to drop row indices low leverages?

This might hide localization in that you might pick a bunch of highly leveraged points but no unleveraged points and thus miss the contrast between the localized and unlocalized entries.

If you share some sample code to create a plot like you want here I can add it to the package in a bit :)
