### ISSUE TITLE
convert Z and Y to matrix?

### ISSUE THREAD

**Issue by karlrohe** [RoheLab/vsp#66]
Z and Y are getting the Matrix type (should I call it "class" or "type"?) inherited from A. However,  the current vsp algorith doesn't make hard zeros in Z and Y.  This makes for frustrating things later on... handing fa$Z to something, expecting it to work, but getting a dumb error like:

cannot coerce class ‘structure("dgeMatrix", package = "Matrix")’ to a data.frame 

Perhaps we convert Z and Y to standard matrix type?

**Comment by alexpghayes** [comment]
This on the todo list. If you want a data frame though just use the `get_*` functions. i.e. https://rohelab.github.io/vsp/reference/get_varimax_y.html

**Comment by alexpghayes** [comment]
Tentatively closing since we have the `get_*` functions.
